# Generated by Django 3.1.5 on 2021-02-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden_compra',
            name='id',
        ),
        migrations.AlterField(
            model_name='orden_compra',
            name='orden',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Órden n° '),
        ),
    ]
