# Generated by Django 3.1.5 on 2021-02-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210201_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orden_compra',
        ),
    ]
