# Generated by Django 3.1.5 on 2021-02-01 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_orden_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden_compra',
            fields=[
                ('orden', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.persona')),
                ('producto', models.ManyToManyField(to='main.Producto')),
            ],
            options={
                'verbose_name_plural': 'Órdenes de compra',
            },
        ),
    ]
