# Generated by Django 3.1.5 on 2021-02-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_orden_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden_compra',
            name='total',
        ),
    ]
