# Generated by Django 3.1.5 on 2021-02-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_orden_compra_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('novedades', models.BooleanField(default=True, verbose_name='Me gustaría recibir novedades de 3DHUB')),
            ],
        ),
        migrations.AlterField(
            model_name='orden_compra',
            name='producto',
            field=models.ManyToManyField(help_text='Selecciona tus productos manteniendo CTRL presionado', to='main.Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
