# Generated by Django 3.1.5 on 2021-02-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210205_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
